[package]
name = "alt"
version = "0.1.0"
authors = ["Itay Garin <thifixp@gmail.com>"]
edition = "2018"

[dependencies]
i3ipc = "0.10.1"
tokio = { version = "0.2", features = ["rt-threaded", "io-util", "macros", "tcp"] }